language: java
os:
- linux
- windows
jdk:
  - oraclejdk8
install: ""
notifications:
    email:
        recipients:
            - marikth@gmail.com
        on_success: change
        on_failure: always
