language: java
os:
- linux
jdk:
  - oraclejdk8
before_script:
  - mysql -e 'create database qnahub_test;'
install: ""
notifications:
    email:
        recipients:
            - marikth@gmail.com
        on_success: change
        on_failure: always
