language: java
os:
- linux
jdk:
  - oraclejdk8
before_script:
  - mysql -u root -e "CREATE USER 'dev_user'@'localhost' IDENTIFIED BY '1234'"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'dev_user'@'localhost'"
install: ""
script: cd QnAHub | mvn install | cd ..
notifications:
    email:
        recipients:
            - marikth@gmail.com
        on_success: change
        on_failure: always
