services:
  - mysql

before_build:
  - cmd: SET MYSQL_PWD="Password12!"
  - cmd: call "C:\Program Files\MySql\MySQL Server 5.7\bin\mysql" -e "CREATE USER 'dev_user'@'localhost' IDENTIFIED BY '1234';" --user=root --password=Password12!
  - cmd: call "C:\Program Files\MySql\MySQL Server 5.7\bin\mysql" -e "GRANT ALL PRIVILEGES ON *.* TO 'dev_user'@'localhost';" --user=root --password=Password12!

version: '{build}'
os: Windows Server 2012
install:

build_script:
  - apache-maven-3.3.9\bin\mvn -f QnAHub/pom.xml install package --batch-mode


cache:
  - C:\maven\
  - C:\Users\appveyor\.m2
